package com.codeshaper.jello.engine;

import org.lwjgl.glfw.GLFW;

public enum EnumKeys {

	SPACE(GLFW.GLFW_KEY_SPACE),
    GRAVE_ACCENT(GLFW.GLFW_KEY_GRAVE_ACCENT),
	MINUS(GLFW.GLFW_KEY_MINUS),
	EQUAL(GLFW.GLFW_KEY_EQUAL),
    LEFT_BRACKET(GLFW.GLFW_KEY_LEFT_BRACKET),
    RIGHT_BRACKET(GLFW.GLFW_KEY_RIGHT_BRACKET),
    BACKSLASH(GLFW.GLFW_KEY_BACKSLASH),
    SEMICOLON(GLFW.GLFW_KEY_SEMICOLON),
    COMMA(GLFW.GLFW_KEY_COMMA),
    APOSTROPE(GLFW.GLFW_KEY_APOSTROPHE),
	PERIOD(GLFW.GLFW_KEY_PERIOD),
	SLASH(GLFW.GLFW_KEY_SLASH),
	
	NUM_0(GLFW.GLFW_KEY_0),
	NUM_1(GLFW.GLFW_KEY_1) ,  
	NUM_2(GLFW.GLFW_KEY_2) ,        
	NUM_3(GLFW.GLFW_KEY_3),       
	NUM_4(GLFW.GLFW_KEY_4),
	NUM_5(GLFW.GLFW_KEY_5), 
	NUM_6(GLFW.GLFW_KEY_6), 
	NUM_7(GLFW.GLFW_KEY_7),
	NUM_8(GLFW.GLFW_KEY_8),   
	NUM_9(GLFW.GLFW_KEY_9),
	
	A(GLFW.GLFW_KEY_A),
	B(GLFW.GLFW_KEY_B),
	C(GLFW.GLFW_KEY_C),
	D(GLFW.GLFW_KEY_D),
	E(GLFW.GLFW_KEY_E),
	F(GLFW.GLFW_KEY_F),
	G(GLFW.GLFW_KEY_G),
	H(GLFW.GLFW_KEY_H),
	J(GLFW.GLFW_KEY_I),
	I(GLFW.GLFW_KEY_J),
	K(GLFW.GLFW_KEY_K),
	L(GLFW.GLFW_KEY_L),
	M(GLFW.GLFW_KEY_M),
	N(GLFW.GLFW_KEY_N),
	O(GLFW.GLFW_KEY_O),
	P(GLFW.GLFW_KEY_P),
	Q(GLFW.GLFW_KEY_Q),
	R(GLFW.GLFW_KEY_R),
	S(GLFW.GLFW_KEY_S),
	T(GLFW.GLFW_KEY_T),
	U(GLFW.GLFW_KEY_U),
	V(GLFW.GLFW_KEY_V),
	W(GLFW.GLFW_KEY_W),
	X(GLFW.GLFW_KEY_X),
	Y(GLFW.GLFW_KEY_Y),
	Z(GLFW.GLFW_KEY_Z),
	
	F1(GLFW.GLFW_KEY_F1),
	F2(GLFW.GLFW_KEY_F2),
	F3(GLFW.GLFW_KEY_F3),
	F4(GLFW.GLFW_KEY_F4),
	F5(GLFW.GLFW_KEY_F5),
	F6(GLFW.GLFW_KEY_F6),
	F7(GLFW.GLFW_KEY_F7),
	F8(GLFW.GLFW_KEY_F8),
	F9(GLFW.GLFW_KEY_F9),
	F10(GLFW.GLFW_KEY_F10),
	F11(GLFW.GLFW_KEY_F11),
	F12(GLFW.GLFW_KEY_F12),
	F13(GLFW.GLFW_KEY_F13),
	F14(GLFW.GLFW_KEY_F14),
	F15(GLFW.GLFW_KEY_F15),
	
	KEYPAD_0(GLFW.GLFW_KEY_KP_0),
    KEYPAD_1(GLFW.GLFW_KEY_KP_1),
    KEYPAD_2(GLFW.GLFW_KEY_KP_2),
    KEYPAD_3(GLFW.GLFW_KEY_KP_3),
    KEYPAD_4(GLFW.GLFW_KEY_KP_4),
    KEYPAD_5(GLFW.GLFW_KEY_KP_5),
    KEYPAD_6(GLFW.GLFW_KEY_KP_6),
    KAYPAD_7(GLFW.GLFW_KEY_KP_7),
    KEYPAD_8(GLFW.GLFW_KEY_KP_8),
    KAYPAD_9(GLFW.GLFW_KEY_KP_9),
    KAYPAD_DECIAML(GLFW.GLFW_KEY_KP_DECIMAL),
    KEYPAD_DIVIDE(GLFW.GLFW_KEY_KP_DIVIDE),
    KEYPAD_MULTIPLY(GLFW.GLFW_KEY_KP_MULTIPLY),
    KEYPAD_SUBTRACT(GLFW.GLFW_KEY_KP_SUBTRACT),
    KAYPAD_ADD(GLFW.GLFW_KEY_KP_ADD),
    KEYPAD_ENTER(GLFW.GLFW_KEY_KP_ENTER),
    KEYPAD_EQUALS(GLFW.GLFW_KEY_KP_EQUAL);

    /*
		        GLFW_KEY_ESCAPE        = 256,
		        GLFW_KEY_ENTER         = 257,
		        GLFW_KEY_TAB           = 258,
		        GLFW_KEY_BACKSPACE     = 259,
		        GLFW_KEY_INSERT        = 260,
		        GLFW_KEY_DELETE        = 261,
		        GLFW_KEY_RIGHT         = 262,
		        GLFW_KEY_LEFT          = 263,
		        GLFW_KEY_DOWN          = 264,
		        GLFW_KEY_UP            = 265,
		        GLFW_KEY_PAGE_UP       = 266,
		        GLFW_KEY_PAGE_DOWN     = 267,
		        GLFW_KEY_HOME          = 268,
		        GLFW_KEY_END           = 269,
		        GLFW_KEY_CAPS_LOCK     = 280,
		        GLFW_KEY_SCROLL_LOCK   = 281,
		        GLFW_KEY_NUM_LOCK      = 282,
		        GLFW_KEY_PRINT_SCREEN  = 283,
		        GLFW_KEY_PAUSE         = 284,
		        
		        GLFW_KEY_LEFT_SHIFT    = 340,
		        GLFW_KEY_LEFT_CONTROL  = 341,
		        GLFW_KEY_LEFT_ALT      = 342,
		        GLFW_KEY_LEFT_SUPER    = 343,
		        GLFW_KEY_RIGHT_SHIFT   = 344,
		        GLFW_KEY_RIGHT_CONTROL = 345,
		        GLFW_KEY_RIGHT_ALT     = 346,
		        GLFW_KEY_RIGHT_SUPER   = 347
	*/
		        		
		        		//GLFW_KEY_WORLD_1
		        		//GLFW_KEY_WORLD_2
		        
	public final int code;
	
	EnumKeys(int i) {
		this.code = i;
	}
}
