package com.codeshaper.jello.engine.rendering.shader;

import static org.lwjgl.opengl.GL42.*;

public enum UniformType {

	float_(GL_FLOAT),
	vec2(GL_FLOAT_VEC2),
	vec3(GL_FLOAT_VEC3),
	vec4(GL_FLOAT_VEC4),
	double_(GL_DOUBLE),
	dvec2(GL_DOUBLE_VEC2),
	dvec3(GL_DOUBLE_VEC3),
	dvec4(GL_DOUBLE_VEC4),
	int_(GL_INT),
	ivec2(GL_INT_VEC2),
	ivec3(GL_INT_VEC3),
	ivec4(GL_INT_VEC4),
	unsigned_int(GL_UNSIGNED_INT),
	uvec2(GL_UNSIGNED_INT_VEC2),
	uvec3(GL_UNSIGNED_INT_VEC3),
	uvec4(GL_UNSIGNED_INT_VEC4),
	bool(GL_BOOL),
	bvec2(GL_BOOL_VEC2),
	bvec3(GL_BOOL_VEC3),
	bvec4(GL_BOOL_VEC4),
	mat2(GL_FLOAT_MAT2),
	mat3(GL_FLOAT_MAT3),
	mat4(GL_FLOAT_MAT4),
	mat2x3(GL_FLOAT_MAT2x3),
	mat2x4(GL_FLOAT_MAT2x4),
	mat3x2(GL_FLOAT_MAT3x2),
	mat3x4(GL_FLOAT_MAT3x4),
	mat4x2(GL_FLOAT_MAT4x2),
	mat4x3(GL_FLOAT_MAT4x3),
	dmat2(GL_DOUBLE_MAT2),
	dmat3(GL_DOUBLE_MAT3),
	dmat4(GL_DOUBLE_MAT4),
	dmat2x3(GL_DOUBLE_MAT2x3),
	dmat2x4(GL_DOUBLE_MAT2x4),
	dmat3x2(GL_DOUBLE_MAT3x2),
	dmat3x4(GL_DOUBLE_MAT3x4),
	dmat4x2(GL_DOUBLE_MAT4x2),
	dmat4x3(GL_DOUBLE_MAT4x3),
	sampler1D(GL_SAMPLER_1D),
	sampler2D(GL_SAMPLER_2D),
	sampler3D(GL_SAMPLER_3D),
	samplerCube(GL_SAMPLER_CUBE),
	sampler1DShadow(GL_SAMPLER_1D_SHADOW),
	sampler2DShadow(GL_SAMPLER_2D_SHADOW),
	sampler1DArray(GL_SAMPLER_1D_ARRAY),
	sampler2DArray(GL_SAMPLER_2D_ARRAY),
	sampler1DArrayShadow(GL_SAMPLER_1D_ARRAY_SHADOW),
	sampler2DArrayShadow(GL_SAMPLER_2D_ARRAY_SHADOW),
	sampler2DMS(GL_SAMPLER_2D_MULTISAMPLE),
	sampler2DMSArray(GL_SAMPLER_2D_MULTISAMPLE_ARRAY),
	samplerCubeShadow(GL_SAMPLER_CUBE_SHADOW),
	samplerBuffer(GL_SAMPLER_BUFFER),
	sampler2DRect(GL_SAMPLER_2D_RECT),
	sampler2DRectShadow(GL_SAMPLER_2D_RECT_SHADOW),
	isampler1D(GL_INT_SAMPLER_1D),
	isampler2D(GL_INT_SAMPLER_2D),
	isampler3D(GL_INT_SAMPLER_3D),
	isamplerCube(GL_INT_SAMPLER_CUBE),
	isampler1DArray(GL_INT_SAMPLER_1D_ARRAY),
	isampler2DArray(GL_INT_SAMPLER_2D_ARRAY),
	isampler2DMS(GL_INT_SAMPLER_2D_MULTISAMPLE),
	isampler2DMSArray(GL_INT_SAMPLER_2D_MULTISAMPLE_ARRAY),
	isamplerBuffer(GL_INT_SAMPLER_BUFFER),
	isampler2DRect(GL_INT_SAMPLER_2D_RECT),
	usampler1D(GL_UNSIGNED_INT_SAMPLER_1D),
	usampler2D(GL_UNSIGNED_INT_SAMPLER_2D),
	usampler3D(GL_UNSIGNED_INT_SAMPLER_3D),
	usamplerCube(GL_UNSIGNED_INT_SAMPLER_CUBE),
	usampler1DArray(GL_UNSIGNED_INT_SAMPLER_1D_ARRAY),
	usampler2DArray(GL_UNSIGNED_INT_SAMPLER_2D_ARRAY),
	usampler2DMS(GL_UNSIGNED_INT_SAMPLER_2D_MULTISAMPLE),
	usampler2DMSArray(GL_UNSIGNED_INT_SAMPLER_2D_MULTISAMPLE_ARRAY),
	usamplerBuffer(GL_UNSIGNED_INT_SAMPLER_BUFFER),
	usampler2DRect(GL_UNSIGNED_INT_SAMPLER_2D_RECT),
	image1D(GL_IMAGE_1D),
	image2D(GL_IMAGE_2D),
	image3D(GL_IMAGE_3D),
	image2DRect(GL_IMAGE_2D_RECT),
	imageCube(GL_IMAGE_CUBE),
	imageBuffer(GL_IMAGE_BUFFER),
	image1DArray(GL_IMAGE_1D_ARRAY),
	image2DArray(GL_IMAGE_2D_ARRAY),
	image2DMS(GL_IMAGE_2D_MULTISAMPLE),
	image2DMSArray(GL_IMAGE_2D_MULTISAMPLE_ARRAY),
	iimage1D(GL_INT_IMAGE_1D),
	iimage2D(GL_INT_IMAGE_2D),
	iimage3D(GL_INT_IMAGE_3D),
	iimage2DRect(GL_INT_IMAGE_2D_RECT),
	iimageCube(GL_INT_IMAGE_CUBE),
	iimageBuffer(GL_INT_IMAGE_BUFFER),
	iimage1DArray(GL_INT_IMAGE_1D_ARRAY),
	iimage2DArray(GL_INT_IMAGE_2D_ARRAY),
	iimage2DMS(GL_INT_IMAGE_2D_MULTISAMPLE),
	iimage2DMSArray(GL_INT_IMAGE_2D_MULTISAMPLE_ARRAY),
	uimage1D(GL_UNSIGNED_INT_IMAGE_1D),
	uimage2D(GL_UNSIGNED_INT_IMAGE_2D),
	uimage3D(GL_UNSIGNED_INT_IMAGE_3D),
	uimage2DRect(GL_UNSIGNED_INT_IMAGE_2D_RECT),
	uimageCube(GL_UNSIGNED_INT_IMAGE_CUBE),
	uimageBuffer(GL_UNSIGNED_INT_IMAGE_BUFFER),
	uimage1DArray(GL_UNSIGNED_INT_IMAGE_1D_ARRAY),
	uimage2DArray(GL_UNSIGNED_INT_IMAGE_2D_ARRAY),
	uimage2DMS(GL_UNSIGNED_INT_IMAGE_2D_MULTISAMPLE),
	uimage2DMSArray(GL_UNSIGNED_INT_IMAGE_2D_MULTISAMPLE_ARRAY),
	atomic_uint(GL_UNSIGNED_INT_ATOMIC_COUNTER);

	public final int type;

	private UniformType(int type) {
		this.type = type;
	}

	public static UniformType from(int type) {
		for (UniformType uniformType : UniformType.values()) {
			if (uniformType.type == type) {
				return uniformType;
			}
		}
		return null;
	}
}